# Generated by Django 3.2.3 on 2021-09-29 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, db_column='FuiId', primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(db_column='FstrYear', default='2000', help_text='年', max_length=4, verbose_name='年')),
                ('month', models.CharField(db_column='FstrMonth', default='01', help_text='月', max_length=2, verbose_name='月')),
                ('day', models.CharField(db_column='FstrDay', default='01', help_text='日', max_length=2, verbose_name='日')),
                ('content', models.TextField(blank=True, db_column='FstrContent', null=True, verbose_name='富文本框内容(HTML)')),
                ('status', models.SmallIntegerField(db_column='FuiStatus', default=1, verbose_name='状态 1:开启,2:关闭')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='FuiCreateTime', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='FuiUpdateTime', verbose_name='更新时间')),
                ('user', models.ForeignKey(db_column='FuiUserId', help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 't_diary_record',
                'ordering': ['id'],
            },
        ),
    ]
