# Generated by Django 3.2.3 on 2021-09-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OmpUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(db_column='FstrEmail', max_length=256, unique=True, verbose_name='登录邮箱')),
                ('name', models.CharField(blank=True, db_column='FstrName', max_length=256, null=True, verbose_name='姓名')),
                ('password', models.CharField(db_column='FstrPassword', max_length=256, verbose_name='密码')),
                ('introduction', models.CharField(db_column='FstrIntroduction', default='', max_length=256, verbose_name='用户描述')),
                ('user_type', models.SmallIntegerField(db_column='FuiUserType', default=1, verbose_name='用户类型 0:超级用户,1:普通用户')),
                ('avatar', models.TextField(blank=True, db_column='FstrAvatar', null=True, verbose_name='头像地址')),
                ('status', models.SmallIntegerField(db_column='FuiStatus', default=0, verbose_name='状态 0:草稿,1:生效,2:失效')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='FuiCreateTime', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='FuiUpdateTime', verbose_name='更新时间')),
            ],
            options={
                'db_table': 't_omp_user_permission',
            },
        ),
    ]
