# Generated by Django 3.2.3 on 2021-09-03 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, db_column='FuiId', primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='FuiYear', default=2000, verbose_name='年份')),
                ('month', models.IntegerField(db_column='FuiMonth', default=1, verbose_name='月份')),
                ('task_name', models.CharField(db_column='FstrTaskName', max_length=256, verbose_name='任务项名称')),
                ('task_type', models.SmallIntegerField(db_column='FuiTaskType', default=0, verbose_name='任务项类型 1:学习 2:工作 3:生活 4:规划')),
                ('target_times', models.IntegerField(db_column='FuiTargetTimes', default=0, verbose_name='目标次数')),
                ('completed_times', models.IntegerField(db_column='FuiCompletedTimes', default=0, verbose_name='完成次数')),
                ('multi_stage', models.CharField(blank=True, db_column='FstrMultiStage', max_length=512, null=True, verbose_name='阶段性目标 json格式')),
                ('remark', models.TextField(blank=True, db_column='FstrRemark', null=True, verbose_name='备注')),
                ('status', models.SmallIntegerField(db_column='FuiStatus', default=1, verbose_name='状态 1:开启,2:关闭')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='FuiCreateTime', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='FuiUpdateTime', verbose_name='更新时间')),
                ('user', models.ForeignKey(db_column='FuiUserId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 't_monthly_plan',
            },
        ),
    ]
