# Generated by Django 3.2.3 on 2021-09-16 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthplan',
            options={'ordering': ['id']},
        ),
    ]
