# Generated by Django 3.2.3 on 2021-10-12 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0002_alter_monthplan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthplan',
            name='status',
            field=models.SmallIntegerField(db_column='FuiStatus', default=1, verbose_name='状态 0:关闭 1:开启,2:废弃'),
        ),
        migrations.CreateModel(
            name='WeekPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, db_column='FuiId', primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_column='FstrTaskName', max_length=256, verbose_name='任务项名称')),
                ('task_type', models.SmallIntegerField(db_column='FuiTaskType', default=0, verbose_name='任务项类型 1:学习 2:工作 3:生活 4:规划')),
                ('start_date', models.DateField(db_column='FdtStartDate', verbose_name='开始时间')),
                ('end_date', models.DateField(db_column='FdtEndDate', verbose_name='结束时间')),
                ('remark', models.TextField(blank=True, db_column='FstrRemark', null=True, verbose_name='备注')),
                ('status', models.SmallIntegerField(db_column='FuiStatus', default=1, verbose_name='状态 0:未完成 1:已完成,2:废弃')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='FuiCreateTime', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='FuiUpdateTime', verbose_name='更新时间')),
                ('user', models.ForeignKey(db_column='FuiUserId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 't_weekly_plan',
                'ordering': ['id'],
            },
        ),
    ]
