# Generated by Django 3.2.3 on 2021-11-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20211012_1834'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='monthplan',
        #     name='multi_stage',
        # ),
        # migrations.AddField(
        #     model_name='monthplan',
        #     name='multi_stages',
        #     field=models.CharField(blank=True, db_column='FstrMultiStages', max_length=512, null=True, verbose_name='阶段性目标 json格式'),
        # ),
        # migrations.AddField(
        #     model_name='monthplan',
        #     name='reward_mechanism',
        #     field=models.SmallIntegerField(db_column='FuiRewardMechanism', default=0, verbose_name='奖励机制 1:一次性 2:阶段性'),
        # ),
        # migrations.AddField(
        #     model_name='monthplan',
        #     name='todo_list',
        #     field=models.TextField(blank=True, db_column='FstrTodoList', null=True, verbose_name='Todo清单 json格式'),
        # ),
    ]
